//! `devy agent-setup`: installs guidance that teaches coding agents to query devy and to
//! run tools in the project environment. `devy init` runs the same setup.

use anyhow::{Context, Result, bail};
use std::path::{Path, PathBuf};

use crate::config::DevyConfig;
use crate::output;

const BINARY: &str = env!("CARGO_PKG_NAME");

const SKILL_TEMPLATE: &str = include_str!("agent_setup/SKILL.md");
const AGENTS_BLOCK_TEMPLATE: &str = include_str!("agent_setup/AGENTS_BLOCK.md");

/// Where the Claude Code skill is written, relative to the project root.
pub const SKILL_PATH: &str = ".claude/skills/devy/SKILL.md";
pub const AGENTS_MD: &str = "AGENTS.md";
const BEGIN: &str = "<!-- devy:begin -->";
const END: &str = "<!-- devy:end -->";

/// `template` with `{bin}` substituted and LF line endings, so the output is identical
/// whichever platform devy was built on (Windows checkouts may convert to CRLF).
fn render(template: &str) -> String {
    template.replace("\r\n", "\n").replace("{bin}", BINARY)
}

/// The skill file's content.
pub fn skill() -> String {
    render(SKILL_TEMPLATE)
}

/// The line that marks a skill file as generated by devy.
fn marker() -> String {
    render("<!-- generated by {bin} agent-setup; rerun to update -->")
}

/// The AGENTS.md block, from `BEGIN` to `END` inclusive, without a trailing newline.
fn agents_block() -> String {
    render(AGENTS_BLOCK_TEMPLATE).trim_end().to_string()
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct Options {
    /// Overwrite a skill file devy didn't write.
    pub force: bool,
    /// Create AGENTS.md when it doesn't exist.
    pub agents_md: bool,
}

/// What happened to one file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Outcome {
    /// Created.
    Wrote,
    /// Changed in place.
    Updated,
    UpToDate,
    /// AGENTS.md doesn't exist and wasn't requested.
    Absent,
    /// The skill exists without devy's marker and `force` wasn't given.
    NotOurs,
    /// AGENTS.md has a begin marker without a matching end marker, or the reverse.
    UnbalancedMarkers,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Report {
    pub skill: Outcome,
    pub agents_md: Outcome,
}

/// A file that couldn't be set up.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Problem {
    pub message: String,
    /// What to run to resolve it, for `devy init`'s warning.
    pub fix: &'static str,
}

impl Report {
    /// Prints a line per file written or already current.
    pub fn print(&self) {
        print_outcome(SKILL_PATH, self.skill);
        print_outcome(AGENTS_MD, self.agents_md);
    }

    pub fn problems(&self) -> Vec<Problem> {
        let mut problems = vec![];
        if self.skill == Outcome::NotOurs {
            problems.push(Problem {
                message: format!("{SKILL_PATH} was not written by devy. Use --force to overwrite."),
                fix: "run devy agent-setup --force to replace it",
            });
        }
        if self.agents_md == Outcome::UnbalancedMarkers {
            problems.push(Problem {
                message: format!(
                    "{AGENTS_MD} has a {BEGIN} marker without a matching {END}, or the reverse. \
                     Fix the markers and rerun devy agent-setup."
                ),
                fix: "fix the markers, then run devy agent-setup",
            });
        }
        problems
    }
}

fn print_outcome(path: &str, outcome: Outcome) {
    match outcome {
        Outcome::Wrote => output::success(&format!("wrote {path}")),
        Outcome::Updated => output::success(&format!("updated {path}")),
        Outcome::UpToDate => output::skip(&format!("{path} is up to date")),
        Outcome::Absent | Outcome::NotOurs | Outcome::UnbalancedMarkers => {}
    }
}

/// Writes the skill and maintains the AGENTS.md block under `root`. Files that can't be
/// set up are reported in the outcome and left unchanged; I/O failures are errors.
pub fn apply(root: &Path, opts: Options) -> Result<Report> {
    Ok(Report {
        skill: apply_skill(root, opts.force)?,
        agents_md: apply_agents_md(root, opts.agents_md)?,
    })
}

fn apply_skill(root: &Path, force: bool) -> Result<Outcome> {
    let path = root.join(SKILL_PATH);
    let content = skill();
    let existing = read_if_exists(&path)?;
    let outcome = match existing {
        Some(old) if old == content => return Ok(Outcome::UpToDate),
        Some(old) if !force && !old.contains(&marker()) => return Ok(Outcome::NotOurs),
        Some(_) => Outcome::Updated,
        None => Outcome::Wrote,
    };
    let dir = path.parent().context("skill path has no parent")?;
    std::fs::create_dir_all(dir).with_context(|| format!("Failed to create {}", dir.display()))?;
    write_atomic(&path, &content)?;
    Ok(outcome)
}

fn apply_agents_md(root: &Path, create: bool) -> Result<Outcome> {
    let path = root.join(AGENTS_MD);
    let block = agents_block();
    let Some(old) = read_if_exists(&path)? else {
        if !create {
            return Ok(Outcome::Absent);
        }
        write_atomic(&path, &format!("{block}\n"))?;
        return Ok(Outcome::Wrote);
    };
    let Some(new) = with_block(&old, &block) else {
        return Ok(Outcome::UnbalancedMarkers);
    };
    if new == old {
        return Ok(Outcome::UpToDate);
    }
    write_atomic(&path, &new)?;
    Ok(Outcome::Updated)
}

/// `content` with exactly one devy block, `block`: the first existing block is replaced
/// in place and any later ones removed, or the block is appended. Everything outside the
/// markers is kept. `None` when the markers are unbalanced.
///
/// Markers count only on a line of their own and outside fenced code blocks, so prose
/// and examples that quote them are left alone. The block takes the file's line endings.
fn with_block(content: &str, block: &str) -> Option<String> {
    let eol = if content.contains("\r\n") {
        "\r\n"
    } else {
        "\n"
    };
    let block = block.replace('\n', eol);
    let mut out = String::with_capacity(content.len() + block.len() + 4);
    let (mut in_fence, mut in_block, mut replaced, mut removed) = (false, false, false, false);
    for line in content.split_inclusive('\n') {
        let text = line.trim();
        if in_block {
            match text {
                END => {
                    in_block = false;
                    if !replaced {
                        out.push_str(&block);
                        // Keep the END line's own line break, or its absence at EOF.
                        out.push_str(&line[line.trim_end().len()..]);
                        replaced = true;
                    } else {
                        removed = true;
                    }
                }
                BEGIN => return None,
                _ => {}
            }
            continue;
        }
        if text.starts_with("```") || text.starts_with("~~~") {
            in_fence = !in_fence;
        } else if !in_fence {
            match text {
                BEGIN => {
                    in_block = true;
                    continue;
                }
                END => return None,
                _ => {}
            }
        }
        out.push_str(line);
    }
    if in_block {
        return None;
    }
    if removed {
        // A removed block leaves the blank line that preceded it at the end of the file.
        let trimmed = out.trim_end().len();
        if trimmed < out.len() {
            out.truncate(trimmed);
            out.push_str(eol);
        }
    }
    if !replaced {
        if !out.is_empty() {
            if !out.ends_with('\n') {
                out.push_str(eol);
            }
            out.push_str(eol);
        }
        out.push_str(&block);
        out.push_str(eol);
    }
    Some(out)
}

fn read_if_exists(path: &Path) -> Result<Option<String>> {
    match std::fs::read_to_string(path) {
        Ok(s) => Ok(Some(s)),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(e).with_context(|| format!("Failed to read {}", path.display())),
    }
}

/// Replaces `path` through a temp file in the same directory, so an interrupted write
/// never leaves it truncated. An existing file keeps its permissions, and a symlink is
/// followed so its target is updated rather than the link replaced by a copy.
fn write_atomic(path: &Path, content: &str) -> Result<()> {
    let target = std::fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf());
    let mut tmp_name = target.file_name().unwrap_or_default().to_os_string();
    tmp_name.push(format!(".{}.tmp", std::process::id()));
    let tmp = target.with_file_name(tmp_name);
    let perms = std::fs::metadata(&target).ok().map(|m| m.permissions());
    let result = std::fs::write(&tmp, content)
        .and_then(|()| match perms {
            Some(perms) => std::fs::set_permissions(&tmp, perms),
            None => Ok(()),
        })
        .and_then(|()| std::fs::rename(&tmp, &target));
    if result.is_err() {
        let _ = std::fs::remove_file(&tmp);
    }
    result.with_context(|| format!("Failed to write {}", path.display()))
}

/// The directory holding the nearest devy.yml.
fn project_root() -> Result<PathBuf> {
    let start = std::env::current_dir().context("Failed to get current directory")?;
    let config = DevyConfig::find_config(&start)
        .ok_or_else(|| anyhow::anyhow!("devy.yml not found — are you inside a devy project?"))?;
    Ok(config
        .parent()
        .context("devy.yml has no parent directory")?
        .to_path_buf())
}

#[cfg_attr(test, mutants::skip)] // thin I/O wrapper — reads the current directory
pub fn run(opts: Options, print: bool) -> Result<()> {
    if print {
        return super::json::write_stdout(&skill());
    }
    run_in(&project_root()?, opts)
}

/// `devy agent-setup` for the project at `root`: fails when a file couldn't be set up.
fn run_in(root: &Path, opts: Options) -> Result<()> {
    let report = apply(root, opts)?;
    report.print();
    let mut problems = report.problems().into_iter();
    match problems.next() {
        None => Ok(()),
        Some(first) => {
            for other in problems {
                output::warn(&other.message);
            }
            bail!(first.message)
        }
    }
}

/// The agent setup `devy init` runs after writing devy.yml in `root`. It never fails:
/// devy.yml is already written, so problems become warnings.
pub fn run_for_init(root: &Path) {
    let problems = match apply(root, Options::default()) {
        Ok(report) => {
            report.print();
            report.problems()
        }
        Err(e) => vec![Problem {
            message: format!("{e:#}"),
            fix: "run devy agent-setup to retry",
        }],
    };
    for problem in problems {
        output::warn(&format!(
            "agent setup skipped: {} — {}",
            problem.message, problem.fix
        ));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn read(root: &Path, path: &str) -> String {
        std::fs::read_to_string(root.join(path)).unwrap()
    }

    // ── templates ────────────────────────────────────────────────────────────

    #[test]
    fn skill_has_frontmatter_and_covers_the_guidance() {
        let skill = skill();
        let rest = skill
            .strip_prefix("---\n")
            .expect("frontmatter opens the file");
        let (frontmatter, body) = rest.split_once("\n---\n").expect("frontmatter closes");
        let fields: Vec<(&str, &str)> = frontmatter
            .lines()
            .map(|l| l.split_once(": ").expect("key: value"))
            .collect();
        assert_eq!(fields[0], ("name", "devy"));
        assert_eq!(fields[1].0, "description");
        assert!(fields[1].1.contains("devy.yml"), "{}", fields[1].1);
        assert_eq!(fields.len(), 2);

        assert!(body.contains(&marker()));
        for needle in [
            "devy status --json",
            "devy services --json",
            "devy exec -- <program>",
            "devy start <name>",
            "devy logs <name>",
            "devy check --json",
            "devy <command>",
            "devy.lock",
            ".shadowenv.d",
        ] {
            assert!(body.contains(needle), "skill must mention {needle}");
        }
        assert!(!skill.contains("{bin}"));
    }

    #[test]
    fn agents_block_is_delimited_by_markers() {
        let block = agents_block();
        assert!(block.starts_with(BEGIN));
        assert!(block.ends_with(END));
        assert_eq!(block.matches(BEGIN).count(), 1);
        for needle in ["devy status --json", "devy exec", "devy check --json"] {
            assert!(block.contains(needle), "block must mention {needle}");
        }
    }

    // ── skill file ───────────────────────────────────────────────────────────

    #[test]
    fn fresh_setup_writes_the_skill_only() {
        let dir = crate::test_support::tmp_dir();
        let report = apply(&dir, Options::default()).unwrap();
        assert_eq!(report.skill, Outcome::Wrote);
        assert_eq!(report.agents_md, Outcome::Absent);
        assert_eq!(read(&dir, SKILL_PATH), skill());
        assert!(!dir.join(AGENTS_MD).exists());
        assert!(report.problems().is_empty());
    }

    #[test]
    fn rerun_is_up_to_date() {
        let dir = crate::test_support::tmp_dir();
        apply(&dir, Options::default()).unwrap();
        let report = apply(&dir, Options::default()).unwrap();
        assert_eq!(report.skill, Outcome::UpToDate);
    }

    #[test]
    fn older_generated_skill_is_regenerated() {
        let dir = crate::test_support::tmp_dir();
        std::fs::create_dir_all(dir.join(".claude/skills/devy")).unwrap();
        let old = format!("---\nname: devy\n---\n{}\nold advice\n", marker());
        std::fs::write(dir.join(SKILL_PATH), old).unwrap();
        let report = apply(&dir, Options::default()).unwrap();
        assert_eq!(report.skill, Outcome::Updated);
        assert_eq!(read(&dir, SKILL_PATH), skill());
    }

    #[test]
    fn hand_written_skill_is_protected_unless_forced() {
        let dir = crate::test_support::tmp_dir();
        std::fs::create_dir_all(dir.join(".claude/skills/devy")).unwrap();
        std::fs::write(dir.join(SKILL_PATH), "my own skill\n").unwrap();

        let err = run_in(&dir, Options::default()).unwrap_err();
        assert_eq!(
            err.to_string(),
            ".claude/skills/devy/SKILL.md was not written by devy. Use --force to overwrite."
        );
        assert_eq!(read(&dir, SKILL_PATH), "my own skill\n");

        run_in(
            &dir,
            Options {
                force: true,
                ..Default::default()
            },
        )
        .unwrap();
        assert_eq!(read(&dir, SKILL_PATH), skill());
    }

    // ── AGENTS.md ────────────────────────────────────────────────────────────

    #[test]
    fn existing_agents_md_gains_the_block() {
        let dir = crate::test_support::tmp_dir();
        std::fs::write(dir.join(AGENTS_MD), "# Agents\n\nUse tabs.\n").unwrap();
        let report = apply(&dir, Options::default()).unwrap();
        assert_eq!(report.agents_md, Outcome::Updated);
        assert_eq!(
            read(&dir, AGENTS_MD),
            format!("# Agents\n\nUse tabs.\n\n{}\n", agents_block())
        );
        let again = apply(&dir, Options::default()).unwrap();
        assert_eq!(again.agents_md, Outcome::UpToDate);
    }

    #[test]
    fn block_is_replaced_in_place() {
        let dir = crate::test_support::tmp_dir();
        std::fs::write(
            dir.join(AGENTS_MD),
            format!("# Agents\n{BEGIN}\nold devy text\n{END}\n\n## Style\nUse tabs.\n"),
        )
        .unwrap();
        apply(&dir, Options::default()).unwrap();
        assert_eq!(
            read(&dir, AGENTS_MD),
            format!("# Agents\n{}\n\n## Style\nUse tabs.\n", agents_block())
        );
    }

    #[test]
    fn duplicate_blocks_collapse_to_one() {
        let doc = format!("a\n{BEGIN}\nx\n{END}\nb\n{BEGIN}\ny\n{END}\nc\n");
        assert_eq!(with_block(&doc, "BLOCK").unwrap(), "a\nBLOCK\nb\nc\n");
    }

    #[test]
    fn unbalanced_markers_fail_without_changes() {
        for doc in [
            format!("a\n{BEGIN}\nno end\n"),
            format!("a\n{END}\n"),
            format!("{BEGIN}\n{BEGIN}\n{END}\n"),
            format!("{END}\n{BEGIN}\n{END}\n"),
        ] {
            let dir = crate::test_support::tmp_dir();
            std::fs::write(dir.join(AGENTS_MD), &doc).unwrap();
            let err = run_in(&dir, Options::default()).unwrap_err();
            assert!(err.to_string().contains("AGENTS.md"), "{err}");
            assert_eq!(read(&dir, AGENTS_MD), doc, "AGENTS.md is left unchanged");
        }
    }

    #[test]
    fn agents_md_created_only_on_request() {
        let dir = crate::test_support::tmp_dir();
        let report = apply(
            &dir,
            Options {
                agents_md: true,
                ..Default::default()
            },
        )
        .unwrap();
        assert_eq!(report.agents_md, Outcome::Wrote);
        assert_eq!(read(&dir, AGENTS_MD), format!("{}\n", agents_block()));
    }

    #[test]
    fn empty_agents_md_gets_just_the_block() {
        assert_eq!(with_block("", "BLOCK").unwrap(), "BLOCK\n");
        assert_eq!(with_block("text", "BLOCK").unwrap(), "text\n\nBLOCK\n");
    }

    #[cfg(unix)]
    #[test]
    fn rewrite_keeps_agents_md_permissions() {
        use std::os::unix::fs::PermissionsExt;
        let dir = crate::test_support::tmp_dir();
        let path = dir.join(AGENTS_MD);
        std::fs::write(&path, "x\n").unwrap();
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600)).unwrap();
        apply(&dir, Options::default()).unwrap();
        let mode = std::fs::metadata(&path).unwrap().permissions().mode();
        assert_eq!(mode & 0o777, 0o600);
        let leftovers: Vec<_> = std::fs::read_dir(&dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| e.file_name().to_string_lossy().ends_with(".tmp"))
            .collect();
        assert!(leftovers.is_empty());
    }

    // ── init ─────────────────────────────────────────────────────────────────

    #[test]
    fn init_setup_warns_instead_of_failing() {
        let dir = crate::test_support::tmp_dir();
        std::fs::create_dir_all(dir.join(".claude/skills/devy")).unwrap();
        std::fs::write(dir.join(SKILL_PATH), "mine\n").unwrap();
        let warnings = output::with_warn_messages(|| run_for_init(&dir));
        assert_eq!(warnings.len(), 1, "{warnings:?}");
        assert!(
            warnings[0].contains("devy agent-setup --force"),
            "{warnings:?}"
        );
        assert_eq!(read(&dir, SKILL_PATH), "mine\n");
    }

    // ── review follow-ups ────────────────────────────────────────────────────

    #[test]
    fn rendered_templates_use_lf_on_every_platform() {
        assert!(!skill().contains('\r'));
        assert!(!agents_block().contains('\r'));
        assert_eq!(render("a\r\nb {bin}\r\n"), "a\nb devy\n");
    }

    #[test]
    fn crlf_agents_md_keeps_crlf() {
        let doc = format!("a\r\n{BEGIN}\r\nold\r\n{END}\r\nb\r\n{BEGIN}\r\ny\r\n{END}\r\nc\r\n");
        assert_eq!(
            with_block(&doc, "B1\nB2").unwrap(),
            "a\r\nB1\r\nB2\r\nb\r\nc\r\n"
        );
        assert_eq!(
            with_block("x\r\n", "B1\nB2").unwrap(),
            "x\r\n\r\nB1\r\nB2\r\n"
        );
    }

    #[test]
    fn markers_in_code_fences_and_prose_are_not_blocks() {
        let doc = format!(
            "Wrap it in `{BEGIN}`.\n```md\n{BEGIN}\nexample\n{END}\n```\n~~~\n{END}\n~~~\n"
        );
        assert_eq!(
            with_block(&doc, "BLOCK").unwrap(),
            format!("{doc}\nBLOCK\n"),
            "quoted and fenced markers are left as is"
        );
    }

    #[test]
    fn indented_markers_still_count() {
        let doc = format!("a\n  {BEGIN}\nold\n  {END}\n");
        assert_eq!(with_block(&doc, "BLOCK").unwrap(), "a\nBLOCK\n");
    }

    #[test]
    fn removing_a_trailing_duplicate_leaves_no_extra_blank_line() {
        let doc = format!("a\n\n{BEGIN}\nx\n{END}\n\n{BEGIN}\ny\n{END}\n");
        assert_eq!(with_block(&doc, "BLOCK").unwrap(), "a\n\nBLOCK\n");
    }

    #[test]
    fn block_at_eof_without_newline_is_replaced() {
        let doc = format!("a\n{BEGIN}\nold\n{END}");
        assert_eq!(with_block(&doc, "BLOCK").unwrap(), "a\nBLOCK");
    }

    #[cfg(unix)]
    #[test]
    fn symlinked_agents_md_updates_its_target() {
        let dir = crate::test_support::tmp_dir();
        std::fs::write(dir.join("CLAUDE.md"), "# Guide\n").unwrap();
        std::os::unix::fs::symlink("CLAUDE.md", dir.join(AGENTS_MD)).unwrap();
        let report = apply(&dir, Options::default()).unwrap();
        assert_eq!(report.agents_md, Outcome::Updated);
        assert!(
            std::fs::symlink_metadata(dir.join(AGENTS_MD))
                .unwrap()
                .file_type()
                .is_symlink(),
            "AGENTS.md is still a link"
        );
        assert_eq!(
            read(&dir, "CLAUDE.md"),
            format!("# Guide\n\n{}\n", agents_block())
        );
    }

    #[cfg(unix)]
    #[test]
    fn symlinked_skill_updates_its_target() {
        let dir = crate::test_support::tmp_dir();
        std::fs::create_dir_all(dir.join(".claude/skills/devy")).unwrap();
        std::fs::write(dir.join("shared-skill.md"), marker()).unwrap();
        std::os::unix::fs::symlink(dir.join("shared-skill.md"), dir.join(SKILL_PATH)).unwrap();
        apply(&dir, Options::default()).unwrap();
        assert!(
            std::fs::symlink_metadata(dir.join(SKILL_PATH))
                .unwrap()
                .file_type()
                .is_symlink()
        );
        assert_eq!(read(&dir, "shared-skill.md"), skill());
    }

    #[test]
    fn init_hint_for_unbalanced_markers() {
        let dir = crate::test_support::tmp_dir();
        std::fs::write(dir.join(AGENTS_MD), format!("{BEGIN}\n")).unwrap();
        let warnings = output::with_warn_messages(|| run_for_init(&dir));
        assert_eq!(warnings.len(), 1, "{warnings:?}");
        assert!(
            warnings[0].ends_with("fix the markers, then run devy agent-setup"),
            "{warnings:?}"
        );
    }
}
