use anyhow::{Context, Result};
use std::path::Path;

use crate::config::DevyConfig;
use crate::modules;
use crate::output;

/// Output format for `devy export`.
#[derive(Debug, Clone, Copy, clap::ValueEnum)]
pub enum ExportFormat {
    /// Generate a `shell.nix` for use with `nix-shell`
    Shell,
    /// Generate a `flake.nix` (default)
    Flake,
}

/// Produces a valid Nix double-quoted string literal from a raw value.
fn nix_string_value(s: &str) -> String {
    let escaped = s
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace("${", "\\${");
    format!("\"{}\"", escaped)
}

/// Returns a Nix attribute name, quoting it if it contains characters that are
/// not valid in a bare Nix identifier.
fn nix_attr_name(k: &str) -> String {
    let is_bare = !k.is_empty()
        && k.bytes().enumerate().all(|(i, b)| {
            b.is_ascii_alphabetic() || b == b'_' || (i > 0 && (b.is_ascii_digit() || b == b'-'))
        });
    if is_bare {
        k.to_string()
    } else {
        format!("\"{}\"", k.replace('"', "\\\""))
    }
}

/// Returns `pkgs.<attr>` lines for each dependency, indented by `indent`, and the
/// attributes among them whose module declares them unfree.
/// A `devy.yml` version that maps to a versioned nixpkgs attribute selects it.
/// Deps whose module returns `None` from `nix_attr` are omitted.
fn collect_pkg_lines(config: &DevyConfig, indent: &str) -> (Vec<String>, Vec<String>) {
    let mut unfree = Vec::new();
    let lines = config
        .dependencies
        .iter()
        .flat_map(|raw| match raw {
            crate::config::RawDependency::Simple(name) => vec![(name.clone(), None)],
            crate::config::RawDependency::Configured(map) => map
                .iter()
                .map(|(name, cfg)| (name.clone(), cfg.as_ref().and_then(|c| c.version.clone())))
                .collect(),
        })
        .filter_map(|(name, version)| {
            let canonical = modules::canonical_name(&name);
            let dep = crate::config::Dependency {
                version,
                ..crate::config::Dependency::simple(canonical)
            };
            let module = modules::get(canonical);
            let attr = module.nix_attr(&dep)?;
            if attr.is_empty() {
                return None;
            }
            // `lib.getName` matches the pname, which equals the attribute for every
            // module that declares itself unfree.
            if module.nix_unfree() && !unfree.contains(&attr) {
                unfree.push(attr.clone());
            }
            Some(format!("{indent}pkgs.{attr}"))
        })
        .collect();
    (lines, unfree)
}

/// `config.allowUnfreePredicate = …;` permitting exactly `unfree`, matched via `get_name`.
fn unfree_predicate(get_name: &str, unfree: &[String]) -> String {
    let names: Vec<String> = unfree.iter().map(|a| nix_string_value(a)).collect();
    format!(
        "config.allowUnfreePredicate = pkg: builtins.elem ({get_name} pkg) [ {} ];",
        names.join(" ")
    )
}

fn generate_shell_nix(config: &DevyConfig) -> String {
    let (pkg_lines, unfree) = collect_pkg_lines(config, "    ");

    let env_lines: Vec<String> = config
        .environment
        .iter()
        .map(|(k, v)| format!("    {} = {};", nix_attr_name(k), nix_string_value(v)))
        .collect();

    let project_name = config.name.as_deref().unwrap_or("project");

    let nixpkgs_args = if unfree.is_empty() {
        "{}".to_string()
    } else {
        format!(
            "{{ {} }}",
            unfree_predicate("(import <nixpkgs/lib>).getName", &unfree)
        )
    };
    let mut out = format!(
        "# Generated by `devy export --format=shell`. Edit to taste.\n\
         {{ pkgs ? import <nixpkgs> {nixpkgs_args} }}:\n\
         \n\
         pkgs.mkShell {{\n\
         \n\
         "
    );

    if !pkg_lines.is_empty() {
        out.push_str("  packages = with pkgs; [\n");
        for line in &pkg_lines {
            out.push_str(line);
            out.push('\n');
        }
        out.push_str("  ];\n\n");
    }

    if !env_lines.is_empty() {
        out.push_str("  # Environment variables\n");
        for line in &env_lines {
            out.push_str("  ");
            out.push_str(line.trim_start());
            out.push('\n');
        }
        out.push('\n');
    }

    out.push_str(&format!(
        "  shellHook = ''\n    echo \"Entered {project_name} dev shell\"\n  '';\n"
    ));

    out.push_str("}\n");
    out
}

fn generate_flake_nix(config: &DevyConfig) -> String {
    let (pkg_lines, unfree) = collect_pkg_lines(config, "          ");

    let env_lines: Vec<String> = config
        .environment
        .iter()
        .map(|(k, v)| format!("          {} = {};", nix_attr_name(k), nix_string_value(v)))
        .collect();

    let project_name = config.name.as_deref().unwrap_or("project");

    let pkgs_expr = if unfree.is_empty() {
        "nixpkgs.legacyPackages.${system}".to_string()
    } else {
        format!(
            "import nixpkgs {{ inherit system; {} }}",
            unfree_predicate("nixpkgs.lib.getName", &unfree)
        )
    };
    let mut out = format!(
        "# Generated by `devy export --format=flake`. Edit to taste.\n\
         {{\n\
           description = \"{project_name} development environment\";\n\
         \n\
           inputs.nixpkgs.url = \"github:NixOS/nixpkgs/nixpkgs-unstable\";\n\
         \n\
           outputs = {{ self, nixpkgs }}:\n\
             let\n\
               forAllSystems = nixpkgs.lib.genAttrs [\n\
                 \"x86_64-linux\" \"aarch64-linux\" \"x86_64-darwin\" \"aarch64-darwin\"\n\
               ];\n\
             in {{\n\
               devShells = forAllSystems (system:\n\
                 let pkgs = {pkgs_expr}; in {{\n\
                   default = pkgs.mkShell {{\n",
    );

    if !pkg_lines.is_empty() {
        out.push_str("            packages = [\n");
        for line in &pkg_lines {
            out.push_str(line);
            out.push('\n');
        }
        out.push_str("            ];\n\n");
    }

    if !env_lines.is_empty() {
        out.push_str("            # Environment variables\n");
        for line in &env_lines {
            out.push_str(line.trim_start());
            out.push('\n');
        }
        out.push('\n');
    }

    out.push_str(&format!(
        "            shellHook = ''\n\
               echo \"Entered {project_name} dev shell\"\n            '';\n"
    ));

    out.push_str("          };\n        });\n    };\n}\n");
    out
}

pub(crate) fn export_impl(
    config: &DevyConfig,
    format: ExportFormat,
    out_path: &Path,
) -> Result<()> {
    let (content, filename) = match format {
        ExportFormat::Shell => (generate_shell_nix(config), "shell.nix"),
        ExportFormat::Flake => (generate_flake_nix(config), "flake.nix"),
    };
    let dest = out_path.join(filename);

    if dest.exists() {
        output::warn(&format!("{} already exists — overwriting", dest.display()));
    }

    std::fs::write(&dest, &content)
        .with_context(|| format!("Failed to write {}", dest.display()))?;

    output::success(&format!("Wrote {}", dest.display()));
    Ok(())
}

#[cfg_attr(test, mutants::skip)] // thin I/O wrapper
pub fn run(format: ExportFormat) -> Result<()> {
    let (config, project_root) = DevyConfig::load_with_root()?;
    output::header("devy export");
    export_impl(&config, format, &project_root)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::DevyConfig;

    fn config_from_yaml(yaml: &str) -> DevyConfig {
        serde_yml::from_str(yaml).unwrap()
    }

    #[test]
    fn module_registry_nix_attrs_are_correct() {
        use crate::config::Dependency;
        use crate::modules;
        let dep = |n| Dependency::simple(n);
        assert_eq!(
            modules::get("redis").nix_attr(&dep("redis")).as_deref(),
            Some("redis")
        );
        assert_eq!(
            modules::get("mysql").nix_attr(&dep("mysql")).as_deref(),
            Some("mysql84")
        );
        assert_eq!(
            modules::get("rabbitmq")
                .nix_attr(&dep("rabbitmq"))
                .as_deref(),
            Some("rabbitmq-server")
        );
        assert_eq!(
            modules::get("mongodb").nix_attr(&dep("mongodb")).as_deref(),
            Some("mongodb-ce")
        );
        assert_eq!(
            modules::get("postgresql")
                .nix_attr(&dep("postgresql"))
                .as_deref(),
            Some("postgresql")
        );
        assert_eq!(
            modules::get("node").nix_attr(&dep("node")).as_deref(),
            Some("nodejs")
        );
        assert_eq!(
            modules::get("rust").nix_attr(&dep("rust")).as_deref(),
            Some("rustup")
        );
        assert_eq!(
            modules::get("python").nix_attr(&dep("python")).as_deref(),
            Some("python3")
        );
        assert_eq!(
            modules::get("go").nix_attr(&dep("go")).as_deref(),
            Some("go")
        );
        assert_eq!(
            modules::get("awscli").nix_attr(&dep("awscli")).as_deref(),
            Some("awscli2")
        );
        assert_eq!(
            modules::get("helm").nix_attr(&dep("helm")).as_deref(),
            Some("kubernetes-helm")
        );
    }

    #[test]
    fn collect_pkg_lines_resolves_aliases() {
        // "postgres" is an alias for "postgresql"; the nix attr must be "postgresql".
        let config = config_from_yaml("dependencies:\n  - postgres\n");
        let (lines, _) = collect_pkg_lines(&config, "");
        assert!(
            lines.iter().any(|l| l.contains("postgresql")),
            "alias 'postgres' must resolve to pkgs.postgresql"
        );
        assert!(
            !lines.iter().any(|l| l.contains("postgres\"")),
            "must not emit pkgs.postgres"
        );
    }

    #[test]
    fn generate_shell_nix_contains_package_entries() {
        let config = config_from_yaml("dependencies:\n  - redis\n  - node\n");
        let out = generate_shell_nix(&config);
        assert!(out.contains("pkgs.redis"), "expected redis in shell.nix");
        assert!(out.contains("pkgs.nodejs"), "expected nodejs in shell.nix");
        assert!(out.contains("mkShell"), "expected mkShell in shell.nix");
    }

    #[test]
    fn generate_flake_nix_contains_package_entries() {
        let config = config_from_yaml("dependencies:\n  - python\n  - postgresql\n");
        let out = generate_flake_nix(&config);
        assert!(out.contains("pkgs.python3"));
        assert!(out.contains("pkgs.postgresql"));
        assert!(out.contains("devShells"));
        assert!(out.contains("nixpkgs-unstable"));
    }

    #[test]
    fn generate_shell_nix_includes_env_vars() {
        let config = config_from_yaml(
            "dependencies:\n  - redis\nenvironment:\n  DATABASE_URL: \"postgres://localhost/dev\"\n",
        );
        let out = generate_shell_nix(&config);
        assert!(
            out.contains("DATABASE_URL = \"postgres://localhost/dev\";"),
            "env var must be properly quoted in shell.nix, got:\n{out}"
        );
    }

    #[test]
    fn nix_string_value_escapes_special_chars() {
        assert_eq!(nix_string_value(r#"say "hi""#), r#""say \"hi\"""#);
        assert_eq!(nix_string_value(r"back\slash"), r#""back\\slash""#);
        assert_eq!(nix_string_value("${FOO}"), r#""\${FOO}""#);
        assert_eq!(nix_string_value("plain"), "\"plain\"");
    }

    #[test]
    fn nix_attr_name_quotes_unsafe_keys() {
        assert_eq!(nix_attr_name("NORMAL_KEY"), "NORMAL_KEY");
        assert_eq!(nix_attr_name("MY-VAR"), "MY-VAR");
        assert_eq!(nix_attr_name("has space"), "\"has space\"");
        assert_eq!(nix_attr_name(""), "\"\"");
        assert_eq!(nix_attr_name("123starts_digit"), "\"123starts_digit\"");
    }

    #[test]
    fn export_impl_shell_writes_file() {
        let dir = crate::test_support::tmp_dir();
        let config = config_from_yaml("dependencies:\n  - redis\n");
        export_impl(&config, ExportFormat::Shell, &dir).unwrap();
        let written = std::fs::read_to_string(dir.join("shell.nix")).unwrap();
        assert!(written.contains("pkgs.redis"));
    }

    #[test]
    fn export_impl_flake_writes_file() {
        let dir = crate::test_support::tmp_dir();
        let config = config_from_yaml("dependencies:\n  - node\n");
        export_impl(&config, ExportFormat::Flake, &dir).unwrap();
        let written = std::fs::read_to_string(dir.join("flake.nix")).unwrap();
        assert!(written.contains("pkgs.nodejs"));
        assert!(written.contains("devShells"));
    }

    #[test]
    fn generate_flake_nix_includes_env_vars() {
        let config =
            config_from_yaml("dependencies:\n  - node\nenvironment:\n  API_KEY: \"secret\"\n");
        let out = generate_flake_nix(&config);
        assert!(
            out.contains("API_KEY = \"secret\";"),
            "env var must be properly quoted in flake.nix, got:\n{out}"
        );
    }

    #[test]
    fn export_impl_warns_on_overwrite() {
        let dir = crate::test_support::tmp_dir();
        let config = config_from_yaml("dependencies:\n  - redis\n");
        // Write the file once to trigger the overwrite branch.
        export_impl(&config, ExportFormat::Shell, &dir).unwrap();
        let warn_count = crate::output::with_warn_capture(|| {
            export_impl(&config, ExportFormat::Shell, &dir).unwrap();
        });
        assert_eq!(warn_count, 1, "must warn exactly once when overwriting");
    }

    #[test]
    fn export_uses_versioned_nix_attributes() {
        let config = config_from_yaml(
            "dependencies:\n  - node:\n      version: \"22\"\n  - python:\n      version: \"3.12.4\"\n  - redis:\n      version: \"7\"\n",
        );
        let out = generate_flake_nix(&config);
        assert!(out.contains("pkgs.nodejs_22"), "{out}");
        assert!(out.contains("pkgs.python312"), "{out}");
        // redis has no versioned attributes: the unversioned one is used.
        assert!(out.contains("pkgs.redis\n"), "{out}");
        let out = generate_shell_nix(&config);
        assert!(out.contains("pkgs.nodejs_22"), "{out}");
    }

    #[test]
    fn mongodb_export_allows_exactly_mongodb_ce() {
        let config = config_from_yaml("dependencies:\n  - mongo\n  - redis\n");
        let pred = r#"config.allowUnfreePredicate = pkg: builtins.elem (nixpkgs.lib.getName pkg) [ "mongodb-ce" ];"#;
        let flake = generate_flake_nix(&config);
        assert!(
            flake.contains(&format!(
                "let pkgs = import nixpkgs {{ inherit system; {pred} }}; in"
            )),
            "{flake}"
        );
        assert!(!flake.contains("legacyPackages"), "{flake}");
        let shell = generate_shell_nix(&config);
        assert!(
            shell.contains(r#"{ pkgs ? import <nixpkgs> { config.allowUnfreePredicate = pkg: builtins.elem ((import <nixpkgs/lib>).getName pkg) [ "mongodb-ce" ]; } }:"#),
            "{shell}"
        );
    }

    #[test]
    fn vault_export_allows_vault() {
        let config = config_from_yaml("dependencies:\n  - vault\n  - terraform\n");
        let shell = generate_shell_nix(&config);
        assert!(shell.contains(r#"[ "vault" "terraform" ]"#), "{shell}");
    }

    #[test]
    fn free_only_export_is_unchanged() {
        let config = config_from_yaml("name: app\ndependencies:\n  - redis\n  - node\n");
        assert_eq!(
            generate_shell_nix(&config),
            "# Generated by `devy export --format=shell`. Edit to taste.\n\
             { pkgs ? import <nixpkgs> {} }:\n\
             \n\
             pkgs.mkShell {\n\
             \n  packages = with pkgs; [\n    pkgs.redis\n    pkgs.nodejs\n  ];\n\n\
             \x20 shellHook = ''\n    echo \"Entered app dev shell\"\n  '';\n}\n"
        );
        let flake = generate_flake_nix(&config);
        assert!(
            flake.contains("let pkgs = nixpkgs.legacyPackages.${system}; in {\n"),
            "{flake}"
        );
        assert!(!flake.contains("allowUnfree"), "{flake}");
    }

    #[test]
    fn unfree_exports_are_well_formed() {
        let config = config_from_yaml("dependencies:\n  - mongodb\n  - elasticsearch\n");
        for (out, file) in [
            (generate_shell_nix(&config), "shell.nix"),
            (generate_flake_nix(&config), "flake.nix"),
        ] {
            assert_eq!(
                out.matches('{').count(),
                out.matches('}').count(),
                "unbalanced braces in {file}:\n{out}"
            );
            assert_eq!(out.matches('[').count(), out.matches(']').count(), "{out}");
            if let Ok(bin) = which::which("nix-instantiate") {
                let dir = crate::test_support::tmp_dir();
                let path = dir.join(file);
                std::fs::write(&path, &out).unwrap();
                let status = std::process::Command::new(bin)
                    .arg("--parse")
                    .arg(&path)
                    .stdout(std::process::Stdio::null())
                    .status()
                    .unwrap();
                assert!(status.success(), "nix-instantiate --parse failed:\n{out}");
            }
        }
    }

    #[test]
    fn generate_shell_nix_is_well_formed() {
        let config =
            config_from_yaml("dependencies:\n  - redis\n  - node\nenvironment:\n  FOO: bar\n");
        let out = generate_shell_nix(&config);
        assert_eq!(
            out.matches('{').count(),
            out.matches('}').count(),
            "unbalanced braces in shell.nix:\n{out}"
        );
        assert!(
            out.ends_with("\n}\n"),
            "shell.nix must end with `}}`:\n{out}"
        );

        // When Nix is installed, confirm the expression actually parses.
        if let Ok(bin) = which::which("nix-instantiate") {
            let dir = crate::test_support::tmp_dir();
            let path = dir.join("shell.nix");
            std::fs::write(&path, &out).unwrap();
            let status = std::process::Command::new(bin)
                .arg("--parse")
                .arg(&path)
                .stdout(std::process::Stdio::null())
                .status()
                .unwrap();
            assert!(status.success(), "nix-instantiate --parse failed:\n{out}");
        }
    }
}
