use anyhow::{Result, anyhow, bail};
use std::path::{Path, PathBuf};

use crate::ai::{self, init_prompt};
use crate::commands::check::static_issues;
use crate::config::DevyConfig;
use crate::init_detect::{self, DETECT_HEADER};
use crate::modules;
use crate::output;

/// How `devy init` produces its config.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mode {
    /// The default: offline detection, then Claude. With `show_context`, print the
    /// request instead of sending it.
    Ai { show_context: bool },
    /// Offline detection only.
    Detect,
}

#[cfg_attr(test, mutants::skip)] // binds the real claude lookup; logic is in run_with
pub fn run(mode: Mode, force: bool, config_path: &Path) -> Result<()> {
    run_with(mode, force, config_path, ai::Client::from_env)
}

/// `run` with the client lookup injected, so tests never run the real `claude`.
fn run_with(
    mode: Mode,
    force: bool,
    config_path: &Path,
    client: impl FnOnce() -> Result<ai::Client>,
) -> Result<()> {
    // Checked before scanning the project or looking for claude.
    if config_path.exists() && !force {
        bail!("devy.yml already exists. Use {} to overwrite.", "--force");
    }

    let dir = project_dir(config_path);
    match mode {
        Mode::Detect => {
            std::fs::write(config_path, init_detect::detect(&dir).render(DETECT_HEADER))?;
            output::success(&format!("wrote {}", config_path.display()));
            Ok(())
        }
        Mode::Ai { show_context: true } => {
            print!(
                "{}",
                init_prompt::request(&dir, ai::model_from_env().as_deref()).render_preview()
            );
            Ok(())
        }
        Mode::Ai {
            show_context: false,
        } => {
            let client = client()
                .map_err(|e| anyhow!("{e} — or run `devy init --detect` to draft one offline"))?;
            run_ai(&client, &dir, config_path)
        }
    }
}

fn ai_header(model: &str) -> String {
    format!("# Generated by devy init ({model}) — AI-generated, review before committing")
}

/// Asks the model for a config, validates it, repairs it at most once, and writes it.
fn run_ai(client: &ai::Client, dir: &Path, config_path: &Path) -> Result<()> {
    output::step(&format!(
        "Drafting devy.yml with claude{}",
        client
            .model
            .as_deref()
            .map(|m| format!(" ({m})"))
            .unwrap_or_default()
    ));
    let request = init_prompt::request(dir, client.model.as_deref());
    let mut reply = client.complete(&request)?;
    let mut yaml = extract_yaml(&reply.text);
    let mut errors = validate(&yaml);
    if !errors.is_empty() {
        output::step("The draft failed validation; asking for a fix");
        let repair = request.follow_up(&reply.text, repair_prompt(&errors));
        reply = client.complete(&repair)?;
        yaml = extract_yaml(&reply.text);
        errors = validate(&yaml);
    }
    if !errors.is_empty() {
        for error in &errors {
            output::warn(error);
        }
        bail!(
            "the AI-generated devy.yml is still invalid, so nothing was written — \
             run `devy init --detect` to draft one offline"
        );
    }

    // Name the model claude actually used; fall back to what was requested.
    let model = reply
        .model
        .or_else(|| client.model.clone())
        .unwrap_or_else(|| "claude".to_string());
    std::fs::write(config_path, format!("{}\n{yaml}", ai_header(&model)))?;
    let config: DevyConfig = serde_yml::from_str(&yaml)?;
    for dep in config.normalized_dependencies()? {
        for warning in modules::get(&dep.name).config_warnings(&dep) {
            output::warn(&format!("{}: {}", dep.name, warning));
        }
    }
    output::success(&format!("wrote {}", config_path.display()));
    Ok(())
}

/// The YAML in the first fenced `yaml` block of `reply`, or the whole reply.
fn extract_yaml(reply: &str) -> String {
    let fenced = ["```yaml", "```yml"].iter().find_map(|fence| {
        let start = reply.find(fence)?;
        let body = &reply[start + fence.len()..];
        let body = &body[body.find('\n')? + 1..];
        Some(body.find("```").map_or(body, |end| &body[..end]))
    });
    let mut yaml = fenced.unwrap_or(reply).trim().to_string();
    yaml.push('\n');
    yaml
}

/// Problems that keep `yaml` from being written: parse errors and static config issues.
fn validate(yaml: &str) -> Vec<String> {
    let config: DevyConfig = match serde_yml::from_str(yaml) {
        Ok(config) => config,
        Err(e) => return vec![format!("devy.yml does not parse: {e}")],
    };
    static_issues(&config).unwrap_or_else(|e| vec![format!("{e:#}")])
}

fn repair_prompt(errors: &[String]) -> String {
    let list: String = errors.iter().map(|e| format!("- {e}\n")).collect();
    format!(
        "devy rejected that devy.yml:\n{list}\nReply with the corrected, complete devy.yml in a single ```yaml fenced block."
    )
}

/// The directory `config_path` lives in; `init` never looks above it.
fn project_dir(config_path: &Path) -> PathBuf {
    match config_path.parent() {
        Some(p) if !p.as_os_str().is_empty() => p.to_path_buf(),
        _ => PathBuf::from("."),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp_config() -> std::path::PathBuf {
        use std::sync::atomic::{AtomicU64, Ordering};
        static N: AtomicU64 = AtomicU64::new(0);
        let dir = std::env::temp_dir().join(format!(
            "devy_init_{}_{}",
            std::process::id(),
            N.fetch_add(1, Ordering::Relaxed)
        ));
        std::fs::create_dir_all(&dir).unwrap();
        dir.join("devy.yml")
    }

    const DEFAULT: Mode = Mode::Ai {
        show_context: false,
    };

    fn fake_client(replies: &[&str]) -> impl FnOnce() -> Result<ai::Client> {
        let fake = crate::ai::fake::FakeTransport::replies(replies);
        move || Ok(ai::Client::with_transport(None, Box::new(fake)))
    }

    fn no_claude() -> Result<ai::Client> {
        Err(anyhow!(ai::MISSING_CLI))
    }

    fn must_not_look_up_claude() -> Result<ai::Client> {
        panic!("claude must not be looked up")
    }

    #[test]
    fn default_mode_writes_ai_config() {
        let path = tmp_config();
        let reply = "```yaml\nname: x\ndependencies: []\n```";
        run_with(DEFAULT, false, &path, fake_client(&[reply])).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.starts_with("# Generated by devy init (claude-sonnet-5-5)"));
        assert!(content.contains("dependencies:"));
    }

    #[test]
    fn default_mode_without_claude_fails_and_suggests_detect() {
        let path = tmp_config();
        let err = run_with(DEFAULT, false, &path, no_claude)
            .unwrap_err()
            .to_string();
        assert!(err.starts_with(ai::MISSING_CLI), "{err}");
        assert!(err.contains("devy init --detect"), "{err}");
        assert!(!path.exists());
    }

    #[test]
    fn run_fails_when_config_exists_without_force() {
        let path = tmp_config();
        std::fs::write(&path, "name: existing\n").unwrap();
        let result = run_with(DEFAULT, false, &path, must_not_look_up_claude);
        assert!(result.unwrap_err().to_string().contains("already exists"));
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "name: existing\n");
    }

    #[test]
    fn run_force_overwrites_existing_config() {
        let path = tmp_config();
        std::fs::write(&path, "name: old\n").unwrap();
        let reply = "name: new\ndependencies: []\n";
        run_with(DEFAULT, true, &path, fake_client(&[reply])).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(!content.contains("name: old") && content.contains("name: new"));
    }

    #[test]
    fn detect_writes_header_and_detected_deps() {
        let path = tmp_config();
        let dir = path.parent().unwrap();
        std::fs::write(dir.join(".nvmrc"), "22\n").unwrap();
        run_with(Mode::Detect, false, &path, must_not_look_up_claude).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.starts_with(DETECT_HEADER), "{content}");
        assert!(
            content.contains("  - node:\n      version: \"22\"\n"),
            "{content}"
        );
    }

    #[test]
    fn detect_refuses_existing_config_without_force() {
        let path = tmp_config();
        std::fs::write(&path, "name: existing\n").unwrap();
        assert!(run_with(Mode::Detect, false, &path, must_not_look_up_claude).is_err());
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "name: existing\n");
    }

    #[test]
    fn project_dir_of_bare_file_name_is_cwd() {
        assert_eq!(project_dir(Path::new("devy.yml")), PathBuf::from("."));
        assert_eq!(project_dir(Path::new("a/devy.yml")), PathBuf::from("a"));
    }

    // ── default (Claude) mode ──────────────────────────────────────────────────────────────

    use crate::ai::fake::FakeTransport;

    const VALID: &str = "```yaml\nname: shop\ndependencies:\n  - redis\n```";
    const TYPO: &str = "Here you go:\n\n```yaml\nname: shop\ndependencies:\n  - redis: { prot: 6380 }\n```\nEnjoy!";

    fn ai_run(replies: &[&str]) -> (Result<()>, FakeTransport, PathBuf, Vec<String>) {
        let path = tmp_config();
        let fake = FakeTransport::replies(replies);
        let client = ai::Client::with_transport(None, Box::new(fake.clone()));
        let mut result = None;
        let warnings = crate::output::with_warn_messages(|| {
            result = Some(run_ai(&client, path.parent().unwrap(), &path));
        });
        (result.unwrap(), fake, path, warnings)
    }

    #[test]
    fn ai_valid_first_reply_is_written_with_header() {
        let (result, fake, path, _) = ai_run(&[VALID]);
        result.unwrap();
        assert_eq!(fake.count(), 1);
        // The model claude reports using, not a hard-coded default.
        let content = std::fs::read_to_string(&path).unwrap();
        assert_eq!(
            content,
            "# Generated by devy init (claude-sonnet-5-5) — AI-generated, review before committing\nname: shop\ndependencies:\n  - redis\n"
        );
        DevyConfig::load(&path).unwrap();
    }

    #[test]
    fn ai_invalid_reply_is_repaired_once() {
        let (result, fake, path, _) = ai_run(&[TYPO, VALID]);
        result.unwrap();
        assert_eq!(fake.count(), 2);
        let repair = fake.stdin(1);
        assert!(
            repair.starts_with(&fake.stdin(0)),
            "repair carries the first prompt"
        );
        assert!(
            repair.contains("=== your previous reply ===\nHere you go:"),
            "{repair}"
        );
        assert!(
            repair.contains("unrecognized config key `prot`"),
            "{repair}"
        );
        assert!(
            std::fs::read_to_string(&path)
                .unwrap()
                .contains("  - redis\n")
        );
    }

    #[test]
    fn ai_invalid_twice_writes_nothing() {
        let (result, fake, path, warnings) = ai_run(&[TYPO, "not: [valid"]);
        let err = result.unwrap_err().to_string();
        assert_eq!(fake.count(), 2);
        assert!(!path.exists());
        assert!(err.contains("devy init --detect"), "{err}");
        assert!(
            warnings.iter().any(|w| w.contains("does not parse")),
            "{warnings:?}"
        );
    }

    #[test]
    fn ai_request_failure_writes_nothing() {
        let path = tmp_config();
        let fake = FakeTransport::new(vec![Ok(crate::ai::fake::error("Not logged in"))]);
        let client = ai::Client::with_transport(None, Box::new(fake));
        let err = run_ai(&client, path.parent().unwrap(), &path).unwrap_err();
        assert_eq!(err.to_string(), "AI request failed: Not logged in");
        assert!(!path.exists());
    }

    #[test]
    fn ai_passes_requested_model_to_claude() {
        let path = tmp_config();
        let fake = FakeTransport::replies(&[VALID]);
        let client = ai::Client::with_transport(Some("claude-opus-5-5"), Box::new(fake.clone()));
        run_ai(&client, path.parent().unwrap(), &path).unwrap();
        assert!(
            fake.args(0)
                .ends_with(&["--model".into(), "claude-opus-5-5".into()])
        );
    }

    #[test]
    fn ai_prints_config_warnings_for_result() {
        let reply = "name: x\ndependencies:\n  - minio:\n      access_key: me\n";
        let (result, _, _, warnings) = ai_run(&[reply]);
        result.unwrap();
        assert!(
            warnings.iter().any(|w| w.starts_with("minio:")),
            "{warnings:?}"
        );
    }

    #[test]
    fn extract_yaml_prefers_fenced_block() {
        assert_eq!(
            extract_yaml(TYPO),
            "name: shop\ndependencies:\n  - redis: { prot: 6380 }\n"
        );
        assert_eq!(extract_yaml("```yml\na: 1\n```"), "a: 1\n");
        assert_eq!(extract_yaml("  name: x\n"), "name: x\n");
    }

    #[test]
    fn validate_reports_parse_and_static_issues() {
        assert!(validate("name: x\ndependencies: []\n").is_empty());
        // service_manager is valid on services and rejected elsewhere.
        assert!(
            validate(
                "service_manager: docker\ndependencies:\n  - redis: { service_manager: package }\n"
            )
            .is_empty()
        );
        let issues = validate("dependencies:\n  - node: { service_manager: docker }\n");
        assert!(
            issues[0].contains("apply only to built-in services"),
            "{issues:?}"
        );
        assert!(validate("bogus_key: 1\n")[0].contains("does not parse"));
        assert_eq!(
            validate("dependencies:\n  - redis: { prot: 6380 }\n").len(),
            1
        );
        assert_eq!(validate("dependencies:\n  - a: {}\n    b: {}\n").len(), 1);
    }
}
