//! Offline detection behind `devy init --detect`: independent detectors read well-known
//! project files from one directory and fill a `Draft`, which renders to a commented
//! `devy.yml`.
//!
//! Only allow-listed files are read. `.env` and other real dotenv files never are.

mod compose;
mod env_example;
mod runtimes;
mod scripts;

use std::path::Path;

use crate::modules;

pub const DETECT_HEADER: &str = "# Generated by devy init --detect — review before committing";

/// The content plain `devy init` writes.
pub const PLAIN_INIT: &str = "name: my-project\n\ndependencies: []\n";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DraftDep {
    pub name: String,
    pub version: Option<String>,
    /// Rendered as `service_manager: docker`.
    pub docker: bool,
}

/// A `devy.yml` under construction. Every list keeps detection order so output is stable.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Draft {
    pub name: Option<String>,
    pub deps: Vec<DraftDep>,
    pub commands: Vec<(String, String)>,
    /// `None` means the value must be filled in by hand.
    pub env: Vec<(String, Option<String>)>,
    pub todos: Vec<String>,
}

impl Draft {
    /// Adds a dependency by canonical name. A later detection of the same module only
    /// fills in a missing version, so earlier detectors take precedence.
    pub fn add_dep(&mut self, name: &str, version: Option<String>) {
        let canonical = modules::canonical_name(name).to_string();
        match self.deps.iter_mut().find(|d| d.name == canonical) {
            Some(existing) => {
                if existing.version.is_none() {
                    existing.version = version;
                }
            }
            None => self.deps.push(DraftDep {
                name: canonical,
                version,
                docker: false,
            }),
        }
    }

    pub fn has_dep(&self, name: &str) -> bool {
        let canonical = modules::canonical_name(name);
        self.deps.iter().any(|d| d.name == canonical)
    }

    pub fn add_command(&mut self, name: &str, cmd: String) {
        if !self.commands.iter().any(|(n, _)| n == name) {
            self.commands.push((name.to_string(), cmd));
        }
    }

    pub fn add_env(&mut self, key: &str, value: Option<String>) {
        if !self.env.iter().any(|(k, _)| k == key) {
            self.env.push((key.to_string(), value));
        }
    }

    pub fn todo(&mut self, msg: String) {
        if !self.todos.contains(&msg) {
            self.todos.push(msg);
        }
    }

    pub fn is_empty(&self) -> bool {
        self.deps.is_empty()
            && self.commands.is_empty()
            && self.env.is_empty()
            && self.todos.is_empty()
    }

    /// Renders the draft as `devy.yml` content beginning with `header`.
    pub fn render(&self, header: &str) -> String {
        let mut out = format!("{header}\n");
        for todo in &self.todos {
            out.push_str(&format!("# TODO: {todo}\n"));
        }
        if self.is_empty() && self.name.is_none() {
            out.push_str(PLAIN_INIT);
            return out;
        }
        out.push_str(&format!(
            "name: {}\n\n",
            scalar(self.name.as_deref().unwrap_or("my-project"))
        ));
        if self.deps.is_empty() {
            out.push_str("dependencies: []\n");
        } else {
            out.push_str("dependencies:\n");
            for dep in &self.deps {
                let mut keys = Vec::new();
                if let Some(v) = &dep.version {
                    keys.push(format!("      version: {}\n", quoted(v)));
                }
                if dep.docker {
                    keys.push("      service_manager: docker\n".to_string());
                }
                if keys.is_empty() {
                    out.push_str(&format!("  - {}\n", scalar(&dep.name)));
                } else {
                    out.push_str(&format!("  - {}:\n{}", scalar(&dep.name), keys.concat()));
                }
            }
        }
        if !self.env.is_empty() {
            out.push_str("\nenvironment:\n");
            for (key, value) in &self.env {
                match value {
                    Some(v) => out.push_str(&format!("  {}: {}\n", scalar(key), quoted(v))),
                    None => out.push_str(&format!("  {}: \"\"  # TODO: set\n", scalar(key))),
                }
            }
        }
        if !self.commands.is_empty() {
            out.push_str("\ncommands:\n");
            for (name, cmd) in &self.commands {
                out.push_str(&format!("  {}: {}\n", scalar(name), quoted(cmd)));
            }
        }
        out
    }
}

/// A plain YAML scalar when that is unambiguous, otherwise a double-quoted one.
fn scalar(s: &str) -> String {
    const RESERVED: &[&str] = &["true", "false", "yes", "no", "on", "off", "null", "y", "n"];
    let plain = s.starts_with(|c: char| c.is_ascii_alphabetic())
        && s.chars()
            .all(|c| c.is_ascii_alphanumeric() || "_.-/@".contains(c))
        && !RESERVED.contains(&s.to_ascii_lowercase().as_str());
    if plain { s.to_string() } else { quoted(s) }
}

/// A double-quoted YAML scalar. JSON string syntax is valid YAML.
fn quoted(s: &str) -> String {
    serde_json::to_string(s).expect("strings always serialize")
}

pub trait Detector {
    fn detect(&self, dir: &Path, draft: &mut Draft);
}

/// Detectors in precedence order: runtime version files first, then services, then the
/// sources that depend on detected services.
const DETECTORS: &[&dyn Detector] = &[
    &runtimes::Node,
    &runtimes::ToolVersions,
    &runtimes::Ruby,
    &runtimes::Python,
    &runtimes::Rust,
    &runtimes::Go,
    &compose::Compose,
    &scripts::PackageScripts,
    &env_example::EnvExample,
];

/// Scans `dir` (not its parents) and returns the draft config.
pub fn detect(dir: &Path) -> Draft {
    let mut draft = Draft::default();
    for detector in DETECTORS {
        detector.detect(dir, &mut draft);
    }
    if !draft.is_empty() {
        draft.name = package_json(dir)
            .and_then(|p| p.get("name")?.as_str().map(String::from))
            .filter(|n| !n.trim().is_empty())
            .or_else(|| dir_name(dir));
    }
    draft
}

fn dir_name(dir: &Path) -> Option<String> {
    let dir = dir.canonicalize().ok()?;
    Some(dir.file_name()?.to_string_lossy().into_owned())
}

/// Reads `dir/name` when it is a regular file. Unreadable files count as absent.
pub(crate) fn read(dir: &Path, name: &str) -> Option<String> {
    let path = dir.join(name);
    if !path.is_file() {
        return None;
    }
    std::fs::read_to_string(path).ok()
}

pub(crate) fn package_json(dir: &Path) -> Option<serde_json::Value> {
    serde_json::from_str(&read(dir, "package.json")?).ok()
}

/// The leading `1.2.3`-style part of `s` after an optional `v`, if it starts with a digit.
pub(crate) fn version_of(s: &str) -> Option<String> {
    let s = s.trim();
    let s = s.strip_prefix('v').unwrap_or(s);
    let v: String = s
        .chars()
        .take_while(|c| c.is_ascii_digit() || *c == '.')
        .collect();
    let v = v.trim_end_matches('.');
    (!v.is_empty()).then(|| v.to_string())
}

#[cfg(test)]
pub(crate) mod test_util {
    use crate::test_support::TempDir;

    pub fn fixture(files: &[(&str, &str)]) -> TempDir {
        let dir = crate::test_support::tmp_dir();
        for (name, content) in files {
            let path = dir.join(name);
            std::fs::create_dir_all(path.parent().unwrap()).unwrap();
            std::fs::write(path, content).unwrap();
        }
        dir
    }
}

#[cfg(test)]
mod tests {
    use super::test_util::fixture;
    use super::*;
    use crate::config::DevyConfig;

    fn parse(yaml: &str) -> DevyConfig {
        let path = crate::test_support::tmp_path(".yml");
        std::fs::write(&path, yaml).unwrap();
        DevyConfig::load(&path).unwrap()
    }

    #[test]
    fn empty_draft_renders_plain_init_with_header() {
        let out = Draft::default().render(DETECT_HEADER);
        assert_eq!(out, format!("{DETECT_HEADER}\n{PLAIN_INIT}"));
        let config = parse(&out);
        assert_eq!(config.name.as_deref(), Some("my-project"));
        assert!(config.dependencies.is_empty());
    }

    #[test]
    fn empty_directory_detects_nothing() {
        let dir = fixture(&[]);
        assert_eq!(detect(&dir), Draft::default());
    }

    #[test]
    fn docker_flag_renders_service_manager() {
        let mut draft = Draft::default();
        draft.add_dep("postgres", Some("16".into()));
        draft.add_dep("redis", None);
        for dep in &mut draft.deps {
            dep.docker = true;
        }
        let out = draft.render(DETECT_HEADER);
        assert!(
            out.contains(
                "  - postgresql:\n      version: \"16\"\n      service_manager: docker\n  - redis:\n      service_manager: docker\n"
            ),
            "{out}"
        );
        let config = parse(&out);
        let deps = config.normalized_dependencies().unwrap();
        assert!(deps.iter().all(|d| d.docker), "{deps:?}");
        assert!(
            crate::commands::check::static_issues(&config)
                .unwrap()
                .is_empty()
        );
    }

    #[test]
    fn full_draft_renders_valid_config() {
        let mut draft = Draft {
            name: Some("my app".into()),
            ..Default::default()
        };
        draft.add_dep("nodejs", Some("22".into()));
        draft.add_dep("redis", None);
        draft.add_dep("node", Some("20".into()));
        draft.add_env(
            "DATABASE_URL",
            Some("postgres://${POSTGRESQL_HOST}/app".into()),
        );
        draft.add_env("API_KEY", None);
        draft.add_command("dev", "npm run dev".into());
        draft.add_command("build:prod", "npm run build:prod".into());
        draft.todo("compose service `api` is unmapped".into());
        let out = draft.render(DETECT_HEADER);
        assert!(out.starts_with(&format!("{DETECT_HEADER}\n# TODO: compose service")));
        assert!(
            out.contains("  - node:\n      version: \"22\"\n  - redis\n"),
            "{out}"
        );
        assert!(out.contains("  API_KEY: \"\"  # TODO: set\n"), "{out}");
        let config = parse(&out);
        assert_eq!(config.name.as_deref(), Some("my app"));
        assert_eq!(
            config.environment["DATABASE_URL"],
            "postgres://${POSTGRESQL_HOST}/app"
        );
        assert_eq!(config.environment["API_KEY"], "");
        let deps = config.normalized_dependencies().unwrap();
        assert_eq!(deps[0].version.as_deref(), Some("22"));
        assert_eq!(config.commands.len(), 2);
        assert!(
            crate::commands::check::static_issues(&config)
                .unwrap()
                .is_empty()
        );
    }

    #[test]
    fn scalar_quotes_ambiguous_values() {
        assert_eq!(scalar("redis"), "redis");
        assert_eq!(scalar("yes"), "\"yes\"");
        assert_eq!(scalar("16"), "\"16\"");
        assert_eq!(scalar("a b"), "\"a b\"");
        assert_eq!(scalar("build:prod"), "\"build:prod\"");
    }

    #[test]
    fn version_of_extracts_leading_version() {
        assert_eq!(version_of("v22.1.0\n").as_deref(), Some("22.1.0"));
        assert_eq!(version_of("3.12.1/envs/x").as_deref(), Some("3.12.1"));
        assert_eq!(version_of("20.x").as_deref(), Some("20"));
        assert_eq!(version_of("lts/iron"), None);
        assert_eq!(version_of("stable"), None);
    }

    #[test]
    fn name_comes_from_package_json_then_directory() {
        let dir = fixture(&[("package.json", r#"{"name":"shop"}"#)]);
        assert_eq!(detect(&dir).name.as_deref(), Some("shop"));
        let dir = fixture(&[("go.mod", "module x\n\ngo 1.22\n")]);
        let expected = dir.canonicalize().unwrap();
        let expected = expected.file_name().unwrap().to_str().unwrap();
        assert_eq!(detect(&dir).name.as_deref(), Some(expected));
    }
}
