use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use serde_norway as yaml;
use std::collections::BTreeMap;
use std::path::Path;

use crate::validate;

pub const PATH: &str = "devy.lock";

fn default_lock_version() -> u32 {
    1
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LockFile {
    #[serde(default = "default_lock_version")]
    pub version: u32,
    pub dependencies: BTreeMap<String, LockedDep>,
}

impl Default for LockFile {
    fn default() -> Self {
        Self {
            version: default_lock_version(),
            dependencies: BTreeMap::new(),
        }
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct LockedDep {
    pub resolved_version: Option<String>,
    /// Install source (e.g. "homebrew", "apt", "rustup", "rbenv").
    /// Recorded for future tooling (e.g. `devy remove`, migration guides).
    /// Not read back by any current command.
    pub source: String,
    /// Port assigned to this service dep. Persisted so the same port is
    /// reused on every subsequent `devy up`, even when no explicit port
    /// is set in devy.yml. User-configured ports in devy.yml always win.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub assigned_port: Option<u16>,
    /// Repository digest (`<repository>@sha256:<hex>`) of a docker-managed service's
    /// image, so teammates run the identical image. Absent for everything else.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub image_digest: Option<String>,
}

/// How to recover from a lock entry that fails validation.
const LOCK_FIX_HINT: &str = "remove that entry, or devy.lock, and run `devy up` to regenerate it";

impl LockFile {
    /// Loads the lock at `path`. A symlinked or non-regular devy.lock is refused before
    /// it is read, so none of its target's text can reach an error message (failure
    /// records and `doctor` send those to claude).
    pub fn load(path: &Path) -> Result<Option<Self>> {
        if std::fs::symlink_metadata(path).is_ok_and(|m| !m.file_type().is_file()) {
            anyhow::bail!("devy.lock is not a regular file (symlinks are refused)");
        }
        let content = match crate::yaml_safe::read_capped(path) {
            Ok(s) => s,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(None),
            Err(e) => return Err(e).context("Failed to read devy.lock"),
        };
        Self::parse(&content).map(Some)
    }

    /// Parses and validates devy.lock content, as [`LockFile::load`] does.
    pub fn parse(content: &str) -> Result<Self> {
        let lock: Self = crate::yaml_safe::from_str_strict(content, "devy.lock")
            .context("Failed to parse devy.lock")?;
        if lock.version != 1 {
            anyhow::bail!(
                "devy.lock has unsupported format version {}. \
                 Only version 1 is supported.",
                lock.version
            );
        }
        if let Err(e) = lock.validate() {
            // The fix travels in the error chain (as context, which callers' own context
            // keeps), never as a side-effect warning: `devy ask` and `doctor` parse locks
            // too, and their output must not gain a stray line.
            return Err(anyhow::anyhow!(
                "Failed to parse devy.lock: {e:#} ({LOCK_FIX_HINT})"
            ));
        }
        Ok(lock)
    }

    /// Checks the fields of every entry that reach process arguments: `resolved_version`
    /// (the project-config version rule), `image_digest` (`<repository>@sha256:<hex>`)
    /// and the range of `assigned_port`. Privileged ports are rejected where a locked port
    /// is actually used, in `commands::ports::resolve_ports`, because an explicit devy.yml
    /// port legitimately records one here and then overrides it.
    fn validate(&self) -> Result<()> {
        for (name, dep) in &self.dependencies {
            // Keys are printed (orphan warnings), so they follow the dependency name rule.
            validate::require(
                validate::dep_name(name),
                "dependencies",
                "dependency name",
                name,
            )?;
            if let Some(v) = dep.resolved_version.as_deref() {
                validate::require(validate::version(v), name, "resolved_version", v)?;
            }
            if let Some(d) = dep.image_digest.as_deref() {
                validate::require(validate::image_digest(d), name, "image_digest", d)?;
            }
            if dep.assigned_port == Some(0) {
                return Err(validate::invalid(name, "assigned_port", "0"));
            }
        }
        Ok(())
    }

    /// Writes the lock to `path`.
    pub fn write(&self, path: &Path) -> Result<()> {
        let body = yaml::to_string(self).context("Failed to serialize lock file")?;
        let content = format!("# Generated by devy — do not edit manually\n{body}");
        crate::fs_safe::write_atomic(path, content.as_bytes(), 0o644)
            .context("Failed to write devy.lock")
    }

    pub fn get(&self, name: &str) -> Option<&LockedDep> {
        self.dependencies.get(name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp_dir() -> crate::test_support::TempDir {
        crate::test_support::tmp_dir()
    }

    fn lock_path(dir: &std::path::Path) -> std::path::PathBuf {
        dir.join(PATH)
    }

    // ── LockFile::get ─────────────────────────────────────────────────────────

    #[test]
    fn get_returns_dep_when_found() {
        let mut deps = BTreeMap::new();
        deps.insert(
            "node".into(),
            LockedDep {
                resolved_version: Some("20.11.0".into()),
                source: "homebrew".into(),
                assigned_port: None,
                image_digest: None,
            },
        );
        deps.insert(
            "redis".into(),
            LockedDep {
                resolved_version: None,
                source: "homebrew".into(),
                assigned_port: None,
                image_digest: None,
            },
        );
        let lock = LockFile {
            dependencies: deps,
            ..Default::default()
        };
        let dep = lock.get("node").unwrap();
        assert_eq!(dep.resolved_version, Some("20.11.0".into()));
    }

    #[test]
    fn get_returns_none_when_not_found() {
        let mut deps = BTreeMap::new();
        deps.insert(
            "node".into(),
            LockedDep {
                resolved_version: None,
                source: "homebrew".into(),
                assigned_port: None,
                image_digest: None,
            },
        );
        let lock = LockFile {
            dependencies: deps,
            ..Default::default()
        };
        assert!(lock.get("mysql").is_none());
    }

    #[test]
    fn get_on_empty_lock_returns_none() {
        let lock = LockFile::default();
        assert!(lock.get("anything").is_none());
    }

    // ── LockFile serde round-trip ─────────────────────────────────────────────

    #[test]
    fn serde_roundtrip_preserves_all_fields() {
        let mut deps = BTreeMap::new();
        deps.insert(
            "node".into(),
            LockedDep {
                resolved_version: Some("20.0.0".into()),
                source: "homebrew".into(),
                assigned_port: None,
                image_digest: None,
            },
        );
        deps.insert(
            "rust".into(),
            LockedDep {
                resolved_version: None,
                source: "rustup".into(),
                assigned_port: None,
                image_digest: None,
            },
        );
        let original = LockFile {
            dependencies: deps,
            ..Default::default()
        };
        let yaml = yaml::to_string(&original).unwrap();
        let parsed: LockFile = yaml::from_str(&yaml).unwrap();
        assert_eq!(parsed.dependencies.len(), 2);
        assert_eq!(
            parsed.get("node").unwrap().resolved_version,
            Some("20.0.0".into())
        );
        assert_eq!(parsed.get("rust").unwrap().source, "rustup");
        assert!(parsed.get("rust").unwrap().resolved_version.is_none());
    }

    #[test]
    fn deserialize_valid_lock_yaml() {
        let yaml = "dependencies:\n  node:\n    resolved_version: '20.0.0'\n    source: homebrew\n";
        let lock: LockFile = yaml::from_str(yaml).unwrap();
        assert_eq!(
            lock.get("node").unwrap().resolved_version,
            Some("20.0.0".into())
        );
    }

    // ── LockFile::write ───────────────────────────────────────────────────────

    #[test]
    fn write_content_includes_header_and_dep_name() {
        let dir = tmp_dir();
        let path = lock_path(&dir);

        let mut deps = BTreeMap::new();
        deps.insert(
            "redis".into(),
            LockedDep {
                resolved_version: Some("7.2.3".into()),
                source: "homebrew".into(),
                assigned_port: None,
                image_digest: None,
            },
        );
        let lock = LockFile {
            dependencies: deps,
            ..Default::default()
        };
        lock.write(&path).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();

        assert!(content.starts_with("# Generated by devy"));
        assert!(content.contains("redis"));
    }

    #[test]
    fn load_returns_none_when_file_absent() {
        let dir = tmp_dir();
        let path = lock_path(&dir);
        assert!(LockFile::load(&path).unwrap().is_none());
    }

    #[test]
    fn write_does_not_leave_tmp_file() {
        let dir = tmp_dir();
        let path = lock_path(&dir);
        let lock = LockFile::default();
        lock.write(&path).unwrap();
        assert!(path.exists(), "lock file must exist after write");
        assert!(
            !path.with_extension("lock.tmp").exists(),
            "temp file must not remain after a successful write"
        );
    }

    #[cfg(unix)]
    #[test]
    fn write_refuses_symlinked_lock() {
        let dir = tmp_dir();
        let outside = tmp_dir();
        let victim = outside.join("victim");
        std::fs::write(&victim, "precious").unwrap();
        let path = lock_path(&dir);
        std::os::unix::fs::symlink(&victim, &path).unwrap();
        let err = format!("{:#}", LockFile::default().write(&path).unwrap_err());
        assert!(err.contains("it is a symbolic link"), "{err}");
        assert_eq!(std::fs::read_to_string(&victim).unwrap(), "precious");
    }

    #[test]
    fn write_leaves_no_temp_files() {
        let dir = tmp_dir();
        let path = lock_path(&dir);
        LockFile::default().write(&path).unwrap();
        LockFile::default().write(&path).unwrap();
        let names: Vec<_> = std::fs::read_dir(&*dir)
            .unwrap()
            .map(|e| e.unwrap().file_name())
            .collect();
        assert_eq!(names, [std::ffi::OsString::from("devy.lock")]);
    }

    #[test]
    fn write_does_not_leave_pid_tmp_file() {
        let dir = tmp_dir();
        let path = lock_path(&dir);
        let lock = LockFile::default();
        lock.write(&path).unwrap();
        assert!(path.exists(), "lock file must exist after write");
        let pid_tmp = path.with_file_name(format!("devy.lock.{}.tmp", std::process::id()));
        assert!(
            !pid_tmp.exists(),
            "PID-namespaced temp file must not remain after a successful write"
        );
    }

    #[test]
    fn load_rejects_future_version() {
        let dir = tmp_dir();
        let path = lock_path(&dir);
        std::fs::write(
            &path,
            "version: 99\ndependencies:\n  node:\n    resolved_version: '20.0.0'\n    source: homebrew\n",
        )
        .unwrap();
        let result = LockFile::load(&path);
        assert!(
            result.is_err(),
            "load must reject lock files from future versions"
        );
        assert!(
            result.unwrap_err().to_string().contains("99"),
            "error must mention the unsupported version number"
        );
    }

    #[test]
    fn load_rejects_version_zero() {
        let dir = tmp_dir();
        let path = lock_path(&dir);
        std::fs::write(
            &path,
            "version: 0\ndependencies:\n  node:\n    resolved_version: '20.0.0'\n    source: homebrew\n",
        )
        .unwrap();
        let result = LockFile::load(&path);
        assert!(
            result.is_err(),
            "load must reject lock files with version 0"
        );
        assert!(
            result.unwrap_err().to_string().contains("0"),
            "error must mention the unsupported version number"
        );
    }

    #[test]
    fn load_accepts_missing_version_as_v1() {
        let dir = tmp_dir();
        let path = lock_path(&dir);
        std::fs::write(
            &path,
            "dependencies:\n  node:\n    resolved_version: '20.0.0'\n    source: homebrew\n",
        )
        .unwrap();
        let lock = LockFile::load(&path).unwrap().unwrap();
        assert_eq!(
            lock.version, 1,
            "lock without version field must default to 1"
        );
        assert!(lock.get("node").is_some());
    }

    #[test]
    fn load_round_trips_written_file() {
        let dir = tmp_dir();
        let path = lock_path(&dir);

        let mut deps = BTreeMap::new();
        deps.insert(
            "pg".into(),
            LockedDep {
                resolved_version: Some("16.0".into()),
                source: "homebrew".into(),
                assigned_port: None,
                image_digest: None,
            },
        );
        let lock = LockFile {
            dependencies: deps,
            ..Default::default()
        };
        lock.write(&path).unwrap();

        let loaded = LockFile::load(&path).unwrap().unwrap();
        assert_eq!(
            loaded.get("pg").unwrap().resolved_version,
            Some("16.0".into())
        );
    }

    // ── image_digest ──────────────────────────────────────────────────────────

    const DIGEST: &str =
        "redis@sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";

    fn docker_redis() -> LockedDep {
        LockedDep {
            resolved_version: Some("7".into()),
            source: "docker".into(),
            assigned_port: Some(51000),
            image_digest: Some(DIGEST.into()),
        }
    }

    #[test]
    fn image_digest_round_trips() {
        let dir = tmp_dir();
        let path = lock_path(&dir);
        let mut deps = BTreeMap::new();
        deps.insert("redis".into(), docker_redis());
        let lock = LockFile {
            dependencies: deps,
            ..Default::default()
        };
        lock.write(&path).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(
            content.contains(&format!("image_digest: {DIGEST}")),
            "{content}"
        );
        assert!(content.contains("source: docker"), "{content}");
        assert_eq!(LockFile::load(&path).unwrap().unwrap(), lock);
    }

    #[test]
    fn package_entries_have_no_image_digest_key() {
        let entry = LockedDep {
            resolved_version: Some("20.11.0".into()),
            source: "homebrew".into(),
            assigned_port: None,
            image_digest: None,
        };
        let yaml = yaml::to_string(&entry).unwrap();
        assert!(!yaml.contains("image_digest"), "{yaml}");
    }

    #[test]
    fn locks_without_image_digest_still_parse() {
        let dir = tmp_dir();
        let path = lock_path(&dir);
        std::fs::write(
            &path,
            "version: 1\ndependencies:\n  redis:\n    resolved_version: 7.2.4\n    source: homebrew\n    assigned_port: 6380\n",
        )
        .unwrap();
        let lock = LockFile::load(&path).unwrap().unwrap();
        assert_eq!(lock.get("redis").unwrap().image_digest, None);
        assert_eq!(lock.get("redis").unwrap().assigned_port, Some(6380));
    }

    // ── entry validation on load ──────────────────────────────────────────────

    fn load_str(content: &str) -> Result<Option<LockFile>> {
        let dir = tmp_dir();
        let path = lock_path(&dir);
        std::fs::write(&path, content).unwrap();
        LockFile::load(&path)
    }

    fn load_err(content: &str) -> String {
        format!("{:#}", load_str(content).unwrap_err())
    }

    #[test]
    fn load_rejects_injected_resolved_version() {
        let err =
            load_err("dependencies:\n  deno:\n    resolved_version: '1.0;id'\n    source: deno\n");
        assert_eq!(
            err,
            format!(
                "Failed to parse devy.lock: deno: invalid resolved_version \"1.0;id\" ({LOCK_FIX_HINT})"
            )
        );
    }

    #[test]
    fn load_rejects_option_like_and_path_versions() {
        for v in [
            "-oDPkg::Pre-Invoke::=id",
            "../../x",
            "lts/iron",
            "16 --force",
        ] {
            let err = load_err(&format!(
                "dependencies:\n  node:\n    resolved_version: '{v}'\n    source: homebrew\n"
            ));
            assert!(err.contains("node: invalid resolved_version"), "{v}: {err}");
        }
    }

    #[test]
    fn load_rejects_malformed_image_digest() {
        for d in [
            "redis@sha256:abc",
            "redis:7",
            "-redis@sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
            "redis@sha256:0123456789ABCDEF0123456789abcdef0123456789abcdef0123456789abcdef",
        ] {
            let err = load_err(&format!(
                "dependencies:\n  redis:\n    resolved_version: '7'\n    source: docker\n    image_digest: '{d}'\n"
            ));
            assert!(
                err.contains("Failed to parse devy.lock: redis: invalid image_digest"),
                "{d}: {err}"
            );
        }
    }

    #[test]
    fn load_accepts_well_formed_image_digest() {
        let lock = load_str(&format!(
            "dependencies:\n  redis:\n    resolved_version: '7'\n    source: docker\n    image_digest: '{DIGEST}'\n"
        ))
        .unwrap()
        .unwrap();
        assert_eq!(
            lock.get("redis").unwrap().image_digest.as_deref(),
            Some(DIGEST)
        );
    }

    #[test]
    fn load_rejects_port_zero() {
        let err = load_err(
            "dependencies:\n  redis:\n    resolved_version: null\n    source: nix\n    assigned_port: 0\n",
        );
        assert!(err.contains("redis: invalid assigned_port"), "{err}");
    }

    #[test]
    fn load_rejects_hostile_dependency_key() {
        let err =
            load_err("dependencies:\n  \"\\e[2Jx\":\n    resolved_version: '1'\n    source: nix\n");
        assert!(
            err.starts_with("Failed to parse devy.lock: dependencies: invalid dependency name"),
            "{err}"
        );
    }

    #[test]
    fn load_rejects_anchors_and_aliases() {
        for doc in [
            crate::test_support::billion_laughs("x"),
            crate::test_support::flat_quadratic("x", 2000, 2000),
            "dependencies:\n  node: &n\n    resolved_version: '20'\n    source: homebrew\n  js: *n\n".to_string(),
        ] {
            let started = std::time::Instant::now();
            let err = load_err(&doc);
            assert!(started.elapsed() < std::time::Duration::from_secs(2));
            assert!(
                err.contains("devy.lock") && err.contains("anchors and aliases are not supported"),
                "{err}"
            );
        }
    }

    #[test]
    fn load_accepts_star_in_quoted_values_and_comments() {
        let lock = load_str(
            "# *comment &x\ndependencies:\n  node:\n    resolved_version: null\n    source: '*home&brew'\n",
        )
        .unwrap()
        .unwrap();
        assert_eq!(lock.get("node").unwrap().source, "*home&brew");
    }

    #[test]
    fn load_rejects_oversized_lock() {
        let doc = format!(
            "# {}\ndependencies: {{}}\n",
            "a".repeat(crate::yaml_safe::MAX_YAML_BYTES)
        );
        let err = load_err(&doc);
        assert!(err.contains("larger than"), "{err}");
    }

    /// The exact bytes `write` produces. A change here changes devy.lock for every
    /// project, so update the expectation only deliberately.
    #[test]
    fn write_output_is_stable() {
        let mut deps = BTreeMap::new();
        deps.insert(
            "node".into(),
            LockedDep {
                resolved_version: Some("20.11.0".into()),
                source: "homebrew".into(),
                assigned_port: None,
                image_digest: None,
            },
        );
        deps.insert("redis".into(), docker_redis());
        deps.insert(
            "rust".into(),
            LockedDep {
                resolved_version: None,
                source: "rustup".into(),
                assigned_port: None,
                image_digest: None,
            },
        );
        let lock = LockFile {
            dependencies: deps,
            ..Default::default()
        };
        let dir = tmp_dir();
        let path = lock_path(&dir);
        lock.write(&path).unwrap();
        let expected = "\
# Generated by devy — do not edit manually
version: 1
dependencies:
  node:
    resolved_version: 20.11.0
    source: homebrew
  redis:
    resolved_version: '7'
    source: docker
    assigned_port: 51000
    image_digest: redis@sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
  rust:
    resolved_version: null
    source: rustup
";
        assert_eq!(std::fs::read_to_string(&path).unwrap(), expected);
    }
}
